mindtrip/quizzes/urls.py
#!/usr/bin/env python
# encoding: utf-8

from django.urls import path
from django.views.generic.base import TemplateView

from . import views


app_name = 'recipes'

urlpatterns = [
    path('', views.get_recipes, name='recipes'),
    path('<int:recipe_id>', views.get_recipe, name='recipe'),
    path('gwara', TemplateView.as_view(template_name='recipes/gwara.html'), name='dialect'),
    path('tagi', views.get_tags, name='tags'),
    path('tagi/<slug:slug>', views.get_tag, name='tag'),
    path('kafelki', views.get_tiles, name='tiles')

]

mindtrip/urls.py
#!/usr/bin/env python
# encoding: utf-8

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView


urlpatterns = [
    path('kurde/', admin.site.urls),
    path('google7daa94b016bce91b.html',
         TemplateView.as_view(template_name='google.html')),

    path('', include('mindtrip.quizzes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mindtrip/quizzes/models.py
#!/usr/bin/env python
# encoding: utf-8

import os

from django.db import models

from .helpers import slugify


def photo_upload_to(instance, filename):
    return os.sep.join(
        ['recipes', str(instance.recipe_id), filename])


class Recipe(models.Model):
    name = models.CharField(max_length=255, verbose_name='Nazwa')
    short = models.CharField(max_length=255, verbose_name='Czas gotowania')
    preparation_before = models.CharField(max_length=255, verbose_name='Czas przygotowania przed gotowaniem właściwym')
    how_much = models.CharField(max_length=255, verbose_name='Ile tego wyjdzie', default="")
    ingredients = models.TextField(verbose_name='Składniki', default="")
    description = models.TextField(verbose_name='Opis')
    added_at = models.DateField(verbose_name='Data dodania')


    tags = models.ManyToManyField('Tag', blank=True, verbose_name='Tagi')

    class Meta:
        verbose_name = 'Przepis'
        verbose_name_plural = 'Przepisy'


    def first_photo(self):
        return self.photos.all().first()

    def __str__(self):
        return self.name


class Photo(models.Model):
    photo = models.ImageField(
        upload_to=photo_upload_to, verbose_name='Zdjęcie')
    recipe = models.ForeignKey(
        Recipe, verbose_name='Przepis', related_name='photos',
        on_delete=models.CASCADE)
    description = models.CharField(
        max_length=255, null=True, blank=True, verbose_name='Opis')

    class Meta:
        verbose_name = 'Zdjęcie'
        verbose_name_plural = 'Zdjęcia'

    def __str__(self):
        return '{0} ({1})'.format(self.recipe, self.photo.url)


class Tag(models.Model):
    name = models.CharField(unique=True, max_length=255, verbose_name='Nazwa')
    slug = models.CharField(max_length=255, blank=True, verbose_name='Slug')

    class Meta:
        abstract = False
        verbose_name = 'Tag'
        verbose_name_plural = 'Tagi'

    def __str__(self):
        return self.name

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(
            force_insert=force_insert, force_update=force_update,
            using=using, update_fields=update_fields)

mindtrip/quizzes/forms.py
#!/usr/bin/env python
# encoding: utf-8

mindtrip/quizzes/views.py
#!/usr/bin/env python
# encoding: utf-8

from annoying.decorators import render_to
from django.shortcuts import get_object_or_404

from .models import Recipe, Tag


@render_to('recipes/recipes.html')
def get_recipes(request):
    return {'recipes': Recipe.objects.all().order_by('-added_at')}


@render_to('recipes/recipe.html')
def get_recipe(request, recipe_id):
    return {'recipe': get_object_or_404(Recipe, id=recipe_id)}


@render_to('recipes/tags.html')
def get_tags(request):
    return {'tags': Tag.objects.all()}


@render_to('recipes/tag.html')
def get_tag(request, slug):
    return {'recipes': Recipe.objects.filter(tags__slug=slug)}

@render_to('recipes/tiles.html')
def get_tiles(request):
    return {'recipes': Recipe.objects.all().order_by('-added_at')}

mindtrip/quizzes/templates/quizzes/gwara.html
{% extends "quizzes/base.html" %}


{% block content %}
	<section id="quiz" class="quiz">
		<h2>Dopasuj słowa z gwary warszawskiej do ich znaczeń</h2>
		<p>Lewym klawiszem myszy przesuwasz kafelki w prawej kolumnie.</p>
		<p>Klikając prawym klawiszem myszy na kafelek w prawej kolumnie zatwierdzasz dopasowanie. Przeskoczy ono do sekcji Gotowe poniżej.</p>
		<p>Klikając na guzik Sprawdź wywołujesz sprawdzenie dopasowań z sekcji Gotowe i wyświetlenie wyniku.</p>
		<div class="gwara">
			<ul id="keys"></ul>
			<ul id="values"></ul>
		</div>
		<p>Gotowe</p>
		<div class="gwara">
			<ul id="ready-keys"></ul>
			<ul id="ready-values"></ul>
		</div>
		<div class="gwara">
			<button type="button" id="check">Sprawdź</button>
			<p id="score"></p>
		</div>
	</section>
	<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	<script src="{{ STATIC_URL }}js/quizzes/jquery-ui.min.js"></script>
	<script src="{{ STATIC_URL }}js/quizzes/gwara.js"></script>

{% endblock %}

mindtrip/quizzes/templates/quizzes/quiz.html
{% extends "quizzes/base.html" %}


{% block content %}
	<section class="quiz">
		<h2>{{ quiz.name }}</h2>
		<h3>{{ quiz.short }}</h3>
		{{ quiz.description|safe }}
		{% if quiz.photos.count %}
			<section class="photos">
				{% for photo in quiz.photos.all %}
					<div class="photo">
						<img src="" data-src="{{ photo.photo.url }}">
						{% if photo.description %}
							<p>{{ photo.description|default_if_none:'' }}</p>
						{% endif %}
					</div>
				{% endfor %}
			</section>
		{% endif %}
	</section>
{% endblock %}

mindtrip/quizzes/templates/quizzes/recipes.html
{% extends "quizzes/base.html" %}


{% block content %}

	<section class="quizzes">
		<h2>Upiecz ciacho</h2>
		<h3><a href="{% url 'recipes:dialect' %}" class="nav-selected">kliknij tu, coby wejsc w gware</a></h3>
		<h2>Quizy</h2>
		{% for quiz in recipes %}
			<section>
				<h3><a href="{% url 'recipes:quiz' quiz.id %}">{{ quiz.added_at|date:"d.m.Y" }} {{ quiz.name }}</a></h3>
				<article>
					{{ quiz.short }}
				</article>
			</section>
		{% endfor %}
		<h3><a href="{% url 'recipes:quiz' 1 %}">{{ quiz.added_at|date:"d.m.Y" }} {{ quiz.name }}</a></h3>
	</section>
{% endblock %}

mindtrip/quizzes/templates/quizzes/tag.html
{% extends "quizzes/base.html" %}


{% block content %}

	<section class="quizzes">
		<h2>Przepisy o tagu</h2>
		{% for recipe in recipes %}
			<section>
				<h3><a href="{% url 'recipes:quiz' quiz_id=recipe.id %}">{{ recipe.name }}</a></h3>
			</section>
		{% endfor %}
	</section>
{% endblock %}

mindtrip/quizzes/templates/quizzes/tags.html
{% extends "quizzes/base.html" %}


{% block content %}

	<section class="quizzes">
		<h2>Tagi</h2>
		{% for tag in tags %}
			<section>
				<h3><a href="">{{ tag.name }}</a></h3>
			</section>
		{% endfor %}
	</section>
{% endblock %}

mindtrip/quizzes/templates/recipes/base.html
<!DOCTYPE html>
<html>
<head lang="pl">
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% endblock %}</title>
	<link href="https://fonts.googleapis.com/css?family=Caveat|Quicksand" rel="stylesheet">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}css/quizzes.css" charset="utf-8">
    <meta name="google-site-verification" content="sKZ_oozUBlXN6Qt_C-Fa55VVfsXoMkpN4ynM3cbKa2c" />
</head>
<body>

	<header>
		<nav>
			<a href="{% url 'recipes:recipes' %}" class="nav-selected">Przepisy</a>
			<a href="{% url 'recipes:tags' %}" class="nav-selected">Tagi</a>
		</nav>
	</header>

	<main>
		<section class="banner">
			longerkowe przepisy <i class="material-icons cake">cake</i>
		</section>
		{% block content %}{% endblock %}
	</main>

	<footer>
		copyright by looongier {% now 'Y' %}
	</footer>

	<script type="text/javascript" src="{{ STATIC_URL }}js/shared/lazy_load_images.js"></script>
</body>
</html>

mindtrip/quizzes/templates/recipes/gwara.html
{% extends "recipes/base.html" %}


{% block content %}
	<section id="quiz" class="quiz">
		<h2>Dopasuj słowa z gwary warszawskiej do ich znaczeń</h2>
		<p>Lewym klawiszem myszy przesuwasz kafelki w prawej kolumnie.</p>
		<p>Klikając prawym klawiszem myszy na kafelek w prawej kolumnie zatwierdzasz dopasowanie. Przeskoczy ono do sekcji Gotowe poniżej.</p>
		<p>Klikając na guzik Sprawdź wywołujesz sprawdzenie dopasowań z sekcji Gotowe i wyświetlenie wyniku.</p>
		<div class="gwara">
			<ul id="keys"></ul>
			<ul id="values"></ul>
		</div>
		<p>Gotowe</p>
		<div class="gwara">
			<ul id="ready-keys"></ul>
			<ul id="ready-values"></ul>
		</div>
		<div class="gwara">
			<button type="button" id="check">Sprawdź</button>
			<p id="score"></p>
		</div>
	</section>
	<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	<script src="{{ STATIC_URL }}js/quizzes/jquery-ui.min.js"></script>
	<script src="{{ STATIC_URL }}js/quizzes/gwara.js"></script>

{% endblock %}

mindtrip/quizzes/templates/recipes/recipe.html
{% extends "recipes/base.html" %}
{% block title %}{{ recipe.name }} - Longerkowe przepisy{% endblock %}

{% block content %}
	<section class="quiz">
		<h2>{{ recipe.name }}</h2>
		<h4>czas przygotowania: <font size="+2">{{ recipe.preparation_before }}</font></h4>
		<h4>czas gotowania: <font size="+2">{{ recipe.short }} </font>minut</h4>
		<br>
		<h3>składniki na {{ recipe.how_much }}:</h3>
		{{ recipe.ingredients|safe }}
		<br>
		{{ recipe.description|safe|linebreaks }}
		{% if recipe.photos.count %}
			<section class="photos">
				{% for photo in recipe.photos.all %}
					<div class="photo">
						<img src="" data-src="{{ photo.photo.url }}">
						{% if photo.description %}
							<p>{{ photo.description|default_if_none:'' }}</p>
						{% endif %}
					</div>
				{% endfor %}
			</section>
		{% endif %}
	</section>
{% endblock %}

mindtrip/quizzes/templates/recipes/recipes.html
{% extends "recipes/base.html" %}

{% block title %}Longerkowe przepisy{% endblock %}

{% block content %}

	<section class="cards">
		{% for quiz in recipes %}
			<article>

				<a href="{% url 'recipes:recipe' quiz.id %}"><img class="article-img" src={{quiz.first_photo.photo.url}}></a>
 				<h3><a class="article-title" href="{% url 'recipes:recipe' quiz.id %}"> {{ quiz.name }} </a></h3>
			</article>
		{% endfor %}
	</section>

{% endblock %}

mindtrip/quizzes/templates/recipes/tag.html
{% extends "recipes/base.html" %}


{% block content %}

	<section class="quizzes">
		<h2>Przepisy o tagu</h2>
		{% for recipe in recipes %}
			<section>
				<h3><a href="{% url 'recipes:recipe' recipe_id=recipe.id %}">{{ recipe.name }}</a></h3>
			</section>
		{% endfor %}
	</section>
{% endblock %}

mindtrip/quizzes/templates/recipes/tags.html
{% extends "recipes/base.html" %}

{% block title %}Tagi - Longerkowe przepisy{% endblock %}

{% block content %}

	<section class="quizzes">
		<h2>Tagi</h2>
		{% for tag in tags %}
			<section>
				<h3><a href="{% url 'recipes:tag' slug=tag.slug %}">{{ tag.name }}</a></h3>
			</section>
		{% endfor %}
	</section>
{% endblock %}

mindtrip/quizzes/templates/recipes/tiles.html
{% extends "recipes/base.html" %}

{% block title %}Longerkowe przepisy{% endblock %}

{% block content %}

	<div class="row">
		{% for quiz in recipes %}
			<div class="box">
				<a href="{% url 'recipes:recipe' quiz.id %}"><img class="article-img" src={{quiz.first_photo.photo.url}} ></a>
				<h3><a class="article-title" href="{% url 'recipes:recipe' quiz.id %}">{{ quiz.added_at|date:"d.m.Y" }} {{ quiz.name }} </a></h3>
			</div>
		{% endfor %}
	</div>

{% endblock %}